name: Deploy Wordpress and a database server to Azure App Service multi-containers
# Use docker-compose-wp.yml as a main docker-compose file

on:
  push:
    branches:
      - main

defaults:
  run:
    # Using a specific shell https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell
    shell: pwsh # Use PowerShell Core

jobs:
  build:
    # Find more virtual environments
    # https://www.dotnetthailand.com/programming-cookbook/github-actions/github-actions-fundamentals#findmorevirtualenvironments
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the latest source code from ${{ github.ref }} commit
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set APP_SERVICE_EXIST variable
        run: |
          # Not output to STDERR and store last exit code to $commandResult 
          $commandResult = & { 
            az webapp show --name cs-multi-containers --resource-group aaron-resource-group 2>&1 | Out-Null;`
            $LastExitCode; `
            $global:LastExitCode = 0;
          }
          if($commandResult -eq 0) { "APP_SERVICE_EXIST=1" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append }

      - name: Publish app service multi-containers
        run: |
          if($env:APP_SERVICE_EXIST -eq 1) {
            "Updating containers with changes in a compose file" 
            az webapp config container set `
              --resource-group aaron-resource-group `
              --name cs-multi-containers `
              --multicontainer-config-type compose `
              --multicontainer-config-file docker-compose-wp.yml
          } else {
            "Creating a new app service with multi-containers"
            az webapp create `
              --resource-group aaron-resource-group `
              --plan cs-container-app-service-plan `
              --name cs-multi-containers `
              --multicontainer-config-type compose `
              --multicontainer-config-file docker-compose-wp.yml
          }
